name: walletconnect_pay
description: "Official Flutter plugin for WalletConnect Pay - enabling wallets to accept crypto and stablecoin payments across multiple blockchain networks."
version: 1.0.0
homepage: https://github.com/reown-com/reown_flutter
repository: https://github.com/reown-com/reown_flutter/tree/develop/packages/walletconnect_pay

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  package_info_plus: '>=8.1.2 <10.0.0'
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.13
  build_version: ^2.1.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.10.0

flutter:
  plugin:
    platforms:
      android:
        package: com.walletconnect.walletconnect_pay
        pluginClass: WalletconnectPayPlugin
      ios:
        pluginClass: WalletconnectPayPlugin
