name: walletconnect_pay_example
description: Example app demonstrating WalletConnect Pay SDK usage.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  walletconnect_pay:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
