// Mocks generated by Mockito 5.4.6 from annotations
// in reown_appkit/test/services/transfers/transfers_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;

import 'package:logger/logger.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:reown_core/connectivity/i_connectivity.dart' as _i6;
import 'package:reown_core/crypto/i_crypto.dart' as _i3;
import 'package:reown_core/echo/i_echo.dart' as _i9;
import 'package:reown_core/events/i_events.dart' as _i10;
import 'package:reown_core/heartbit/i_heartbeat.dart' as _i2;
import 'package:reown_core/i_core_impl.dart' as _i14;
import 'package:reown_core/pairing/i_expirer.dart' as _i7;
import 'package:reown_core/pairing/i_pairing.dart' as _i8;
import 'package:reown_core/relay_client/i_relay_client.dart' as _i4;
import 'package:reown_core/store/i_store.dart' as _i5;
import 'package:reown_core/store/link_mode_store.dart' as _i13;
import 'package:reown_core/verify/i_verify.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIHeartBeat_0 extends _i1.SmartFake implements _i2.IHeartBeat {
  _FakeIHeartBeat_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeICrypto_1 extends _i1.SmartFake implements _i3.ICrypto {
  _FakeICrypto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIRelayClient_2 extends _i1.SmartFake implements _i4.IRelayClient {
  _FakeIRelayClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIStore_3<T> extends _i1.SmartFake implements _i5.IStore<T> {
  _FakeIStore_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIConnectivity_4 extends _i1.SmartFake implements _i6.IConnectivity {
  _FakeIConnectivity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIExpirer_5 extends _i1.SmartFake implements _i7.IExpirer {
  _FakeIExpirer_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIPairing_6 extends _i1.SmartFake implements _i8.IPairing {
  _FakeIPairing_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIEcho_7 extends _i1.SmartFake implements _i9.IEcho {
  _FakeIEcho_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIEvents_8 extends _i1.SmartFake implements _i10.IEvents {
  _FakeIEvents_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogger_9 extends _i1.SmartFake implements _i11.Logger {
  _FakeLogger_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIVerify_10 extends _i1.SmartFake implements _i12.IVerify {
  _FakeIVerify_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeILinkModeStore_11 extends _i1.SmartFake
    implements _i13.ILinkModeStore {
  _FakeILinkModeStore_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IReownCore].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReownCore extends _i1.Mock implements _i14.IReownCore {
  MockIReownCore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get protocol =>
      (super.noSuchMethod(
            Invocation.getter(#protocol),
            returnValue: _i15.dummyValue<String>(
              this,
              Invocation.getter(#protocol),
            ),
          )
          as String);

  @override
  String get version =>
      (super.noSuchMethod(
            Invocation.getter(#version),
            returnValue: _i15.dummyValue<String>(
              this,
              Invocation.getter(#version),
            ),
          )
          as String);

  @override
  String get relayUrl =>
      (super.noSuchMethod(
            Invocation.getter(#relayUrl),
            returnValue: _i15.dummyValue<String>(
              this,
              Invocation.getter(#relayUrl),
            ),
          )
          as String);

  @override
  String get projectId =>
      (super.noSuchMethod(
            Invocation.getter(#projectId),
            returnValue: _i15.dummyValue<String>(
              this,
              Invocation.getter(#projectId),
            ),
          )
          as String);

  @override
  String get pushUrl =>
      (super.noSuchMethod(
            Invocation.getter(#pushUrl),
            returnValue: _i15.dummyValue<String>(
              this,
              Invocation.getter(#pushUrl),
            ),
          )
          as String);

  @override
  _i2.IHeartBeat get heartbeat =>
      (super.noSuchMethod(
            Invocation.getter(#heartbeat),
            returnValue: _FakeIHeartBeat_0(this, Invocation.getter(#heartbeat)),
          )
          as _i2.IHeartBeat);

  @override
  _i3.ICrypto get crypto =>
      (super.noSuchMethod(
            Invocation.getter(#crypto),
            returnValue: _FakeICrypto_1(this, Invocation.getter(#crypto)),
          )
          as _i3.ICrypto);

  @override
  _i4.IRelayClient get relayClient =>
      (super.noSuchMethod(
            Invocation.getter(#relayClient),
            returnValue: _FakeIRelayClient_2(
              this,
              Invocation.getter(#relayClient),
            ),
          )
          as _i4.IRelayClient);

  @override
  _i5.IStore<Map<String, dynamic>> get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeIStore_3<Map<String, dynamic>>(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i5.IStore<Map<String, dynamic>>);

  @override
  _i5.IStore<Map<String, dynamic>> get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeIStore_3<Map<String, dynamic>>(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i5.IStore<Map<String, dynamic>>);

  @override
  _i6.IConnectivity get connectivity =>
      (super.noSuchMethod(
            Invocation.getter(#connectivity),
            returnValue: _FakeIConnectivity_4(
              this,
              Invocation.getter(#connectivity),
            ),
          )
          as _i6.IConnectivity);

  @override
  _i7.IExpirer get expirer =>
      (super.noSuchMethod(
            Invocation.getter(#expirer),
            returnValue: _FakeIExpirer_5(this, Invocation.getter(#expirer)),
          )
          as _i7.IExpirer);

  @override
  _i8.IPairing get pairing =>
      (super.noSuchMethod(
            Invocation.getter(#pairing),
            returnValue: _FakeIPairing_6(this, Invocation.getter(#pairing)),
          )
          as _i8.IPairing);

  @override
  _i9.IEcho get echo =>
      (super.noSuchMethod(
            Invocation.getter(#echo),
            returnValue: _FakeIEcho_7(this, Invocation.getter(#echo)),
          )
          as _i9.IEcho);

  @override
  _i10.IEvents get events =>
      (super.noSuchMethod(
            Invocation.getter(#events),
            returnValue: _FakeIEvents_8(this, Invocation.getter(#events)),
          )
          as _i10.IEvents);

  @override
  _i11.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_9(this, Invocation.getter(#logger)),
          )
          as _i11.Logger);

  @override
  _i12.IVerify get verify =>
      (super.noSuchMethod(
            Invocation.getter(#verify),
            returnValue: _FakeIVerify_10(this, Invocation.getter(#verify)),
          )
          as _i12.IVerify);

  @override
  _i13.ILinkModeStore get linkModeStore =>
      (super.noSuchMethod(
            Invocation.getter(#linkModeStore),
            returnValue: _FakeILinkModeStore_11(
              this,
              Invocation.getter(#linkModeStore),
            ),
          )
          as _i13.ILinkModeStore);

  @override
  set relayUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#relayUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  set heartbeat(_i2.IHeartBeat? value) => super.noSuchMethod(
    Invocation.setter(#heartbeat, value),
    returnValueForMissingStub: null,
  );

  @override
  set crypto(_i3.ICrypto? value) => super.noSuchMethod(
    Invocation.setter(#crypto, value),
    returnValueForMissingStub: null,
  );

  @override
  set relayClient(_i4.IRelayClient? value) => super.noSuchMethod(
    Invocation.setter(#relayClient, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i5.IStore<Map<String, dynamic>>? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set secureStorage(_i5.IStore<Map<String, dynamic>>? value) =>
      super.noSuchMethod(
        Invocation.setter(#secureStorage, value),
        returnValueForMissingStub: null,
      );

  @override
  set connectivity(_i6.IConnectivity? value) => super.noSuchMethod(
    Invocation.setter(#connectivity, value),
    returnValueForMissingStub: null,
  );

  @override
  set expirer(_i7.IExpirer? value) => super.noSuchMethod(
    Invocation.setter(#expirer, value),
    returnValueForMissingStub: null,
  );

  @override
  set pairing(_i8.IPairing? value) => super.noSuchMethod(
    Invocation.setter(#pairing, value),
    returnValueForMissingStub: null,
  );

  @override
  set echo(_i9.IEcho? value) => super.noSuchMethod(
    Invocation.setter(#echo, value),
    returnValueForMissingStub: null,
  );

  @override
  set events(_i10.IEvents? value) => super.noSuchMethod(
    Invocation.setter(#events, value),
    returnValueForMissingStub: null,
  );

  @override
  set verify(_i12.IVerify? value) => super.noSuchMethod(
    Invocation.setter(#verify, value),
    returnValueForMissingStub: null,
  );

  @override
  set linkModeStore(_i13.ILinkModeStore? value) => super.noSuchMethod(
    Invocation.setter(#linkModeStore, value),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void confirmOnlineStateOrThrow() => super.noSuchMethod(
    Invocation.method(#confirmOnlineStateOrThrow, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<bool> addLinkModeSupportedApp(String? universalLink) =>
      (super.noSuchMethod(
            Invocation.method(#addLinkModeSupportedApp, [universalLink]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  List<String> getLinkModeSupportedApps() =>
      (super.noSuchMethod(
            Invocation.method(#getLinkModeSupportedApps, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  void addLogListener(dynamic Function(String)? callback) => super.noSuchMethod(
    Invocation.method(#addLogListener, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  bool removeLogListener(dynamic Function(String)? callback) =>
      (super.noSuchMethod(
            Invocation.method(#removeLogListener, [callback]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i11.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<void> get init =>
      (super.noSuchMethod(
            Invocation.getter(#init),
            returnValue: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void v(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #v,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void t(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #t,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void d(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #d,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void i(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #i,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void w(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #w,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void e(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #e,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void wtf(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #wtf,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void f(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #f,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void log(
    _i11.Level? level,
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #log,
      [level, message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool isClosed() =>
      (super.noSuchMethod(Invocation.method(#isClosed, []), returnValue: false)
          as bool);

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}
