// Mocks generated by Mockito 5.4.6 from annotations
// in reown_appkit/test/services/dwe/dwe_service_transfers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i21;

import 'package:event/event.dart' as _i3;
import 'package:logger/logger.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:reown_appkit/base/i_appkit_base_impl.dart' as _i18;
import 'package:reown_appkit/base/services/models/asset_models.dart' as _i20;
import 'package:reown_appkit/base/services/models/query_models.dart' as _i23;
import 'package:reown_appkit/base/services/models/result_models.dart' as _i22;
import 'package:reown_appkit/modal/services/transfers/i_transfers_service.dart'
    as _i24;
import 'package:reown_appkit/modal/services/transfers/models/quote_models.dart'
    as _i27;
import 'package:reown_appkit/modal/services/transfers/models/quote_params.dart'
    as _i26;
import 'package:reown_appkit/modal/services/transfers/models/quote_results.dart'
    as _i25;
import 'package:reown_core/connectivity/i_connectivity.dart' as _i10;
import 'package:reown_core/crypto/i_crypto.dart' as _i7;
import 'package:reown_core/echo/i_echo.dart' as _i13;
import 'package:reown_core/events/i_events.dart' as _i14;
import 'package:reown_core/heartbit/i_heartbeat.dart' as _i6;
import 'package:reown_core/pairing/i_expirer.dart' as _i11;
import 'package:reown_core/pairing/i_pairing.dart' as _i12;
import 'package:reown_core/relay_client/i_relay_client.dart' as _i8;
import 'package:reown_core/reown_core.dart' as _i4;
import 'package:reown_core/store/i_generic_store.dart' as _i5;
import 'package:reown_core/store/i_store.dart' as _i9;
import 'package:reown_core/store/link_mode_store.dart' as _i17;
import 'package:reown_core/verify/i_verify.dart' as _i16;
import 'package:reown_sign/reown_sign.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIReownSign_0 extends _i1.SmartFake implements _i2.IReownSign {
  _FakeIReownSign_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvent_1<T extends _i3.EventArgs> extends _i1.SmartFake
    implements _i3.Event<T> {
  _FakeEvent_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIReownCore_2 extends _i1.SmartFake implements _i4.IReownCore {
  _FakeIReownCore_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIGenericStore_3<T> extends _i1.SmartFake
    implements _i5.IGenericStore<T> {
  _FakeIGenericStore_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeISessions_4 extends _i1.SmartFake implements _i2.ISessions {
  _FakeISessions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIPairingStore_5 extends _i1.SmartFake implements _i4.IPairingStore {
  _FakeIPairingStore_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConnectResponse_6 extends _i1.SmartFake
    implements _i2.ConnectResponse {
  _FakeConnectResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionAuthRequestResponse_7 extends _i1.SmartFake
    implements _i2.SessionAuthRequestResponse {
  _FakeSessionAuthRequestResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIHeartBeat_8 extends _i1.SmartFake implements _i6.IHeartBeat {
  _FakeIHeartBeat_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeICrypto_9 extends _i1.SmartFake implements _i7.ICrypto {
  _FakeICrypto_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIRelayClient_10 extends _i1.SmartFake implements _i8.IRelayClient {
  _FakeIRelayClient_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIStore_11<T> extends _i1.SmartFake implements _i9.IStore<T> {
  _FakeIStore_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIConnectivity_12 extends _i1.SmartFake
    implements _i10.IConnectivity {
  _FakeIConnectivity_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIExpirer_13 extends _i1.SmartFake implements _i11.IExpirer {
  _FakeIExpirer_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIPairing_14 extends _i1.SmartFake implements _i12.IPairing {
  _FakeIPairing_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIEcho_15 extends _i1.SmartFake implements _i13.IEcho {
  _FakeIEcho_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIEvents_16 extends _i1.SmartFake implements _i14.IEvents {
  _FakeIEvents_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogger_17 extends _i1.SmartFake implements _i15.Logger {
  _FakeLogger_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIVerify_18 extends _i1.SmartFake implements _i16.IVerify {
  _FakeIVerify_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeILinkModeStore_19 extends _i1.SmartFake
    implements _i17.ILinkModeStore {
  _FakeILinkModeStore_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IReownAppKit].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReownAppKit extends _i1.Mock implements _i18.IReownAppKit {
  MockIReownAppKit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get protocol =>
      (super.noSuchMethod(
            Invocation.getter(#protocol),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#protocol),
            ),
          )
          as String);

  @override
  int get version =>
      (super.noSuchMethod(Invocation.getter(#version), returnValue: 0) as int);

  @override
  _i2.IReownSign get reOwnSign =>
      (super.noSuchMethod(
            Invocation.getter(#reOwnSign),
            returnValue: _FakeIReownSign_0(this, Invocation.getter(#reOwnSign)),
          )
          as _i2.IReownSign);

  @override
  _i3.Event<_i2.SessionUpdate> get onSessionUpdate =>
      (super.noSuchMethod(
            Invocation.getter(#onSessionUpdate),
            returnValue: _FakeEvent_1<_i2.SessionUpdate>(
              this,
              Invocation.getter(#onSessionUpdate),
            ),
          )
          as _i3.Event<_i2.SessionUpdate>);

  @override
  _i3.Event<_i2.SessionExtend> get onSessionExtend =>
      (super.noSuchMethod(
            Invocation.getter(#onSessionExtend),
            returnValue: _FakeEvent_1<_i2.SessionExtend>(
              this,
              Invocation.getter(#onSessionExtend),
            ),
          )
          as _i3.Event<_i2.SessionExtend>);

  @override
  _i3.Event<_i2.SessionEvent> get onSessionEvent =>
      (super.noSuchMethod(
            Invocation.getter(#onSessionEvent),
            returnValue: _FakeEvent_1<_i2.SessionEvent>(
              this,
              Invocation.getter(#onSessionEvent),
            ),
          )
          as _i3.Event<_i2.SessionEvent>);

  @override
  _i3.Event<_i2.SessionAuthResponse> get onSessionAuthResponse =>
      (super.noSuchMethod(
            Invocation.getter(#onSessionAuthResponse),
            returnValue: _FakeEvent_1<_i2.SessionAuthResponse>(
              this,
              Invocation.getter(#onSessionAuthResponse),
            ),
          )
          as _i3.Event<_i2.SessionAuthResponse>);

  @override
  _i3.Event<_i2.SessionConnect> get onSessionConnect =>
      (super.noSuchMethod(
            Invocation.getter(#onSessionConnect),
            returnValue: _FakeEvent_1<_i2.SessionConnect>(
              this,
              Invocation.getter(#onSessionConnect),
            ),
          )
          as _i3.Event<_i2.SessionConnect>);

  @override
  _i3.Event<_i2.SessionDelete> get onSessionDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onSessionDelete),
            returnValue: _FakeEvent_1<_i2.SessionDelete>(
              this,
              Invocation.getter(#onSessionDelete),
            ),
          )
          as _i3.Event<_i2.SessionDelete>);

  @override
  _i3.Event<_i2.SessionExpire> get onSessionExpire =>
      (super.noSuchMethod(
            Invocation.getter(#onSessionExpire),
            returnValue: _FakeEvent_1<_i2.SessionExpire>(
              this,
              Invocation.getter(#onSessionExpire),
            ),
          )
          as _i3.Event<_i2.SessionExpire>);

  @override
  _i3.Event<_i2.SessionPing> get onSessionPing =>
      (super.noSuchMethod(
            Invocation.getter(#onSessionPing),
            returnValue: _FakeEvent_1<_i2.SessionPing>(
              this,
              Invocation.getter(#onSessionPing),
            ),
          )
          as _i3.Event<_i2.SessionPing>);

  @override
  _i3.Event<_i2.SessionProposalEvent> get onProposalExpire =>
      (super.noSuchMethod(
            Invocation.getter(#onProposalExpire),
            returnValue: _FakeEvent_1<_i2.SessionProposalEvent>(
              this,
              Invocation.getter(#onProposalExpire),
            ),
          )
          as _i3.Event<_i2.SessionProposalEvent>);

  @override
  _i4.IReownCore get core =>
      (super.noSuchMethod(
            Invocation.getter(#core),
            returnValue: _FakeIReownCore_2(this, Invocation.getter(#core)),
          )
          as _i4.IReownCore);

  @override
  _i4.PairingMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _i19.dummyValue<_i4.PairingMetadata>(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i4.PairingMetadata);

  @override
  _i5.IGenericStore<_i2.ProposalData> get proposals =>
      (super.noSuchMethod(
            Invocation.getter(#proposals),
            returnValue: _FakeIGenericStore_3<_i2.ProposalData>(
              this,
              Invocation.getter(#proposals),
            ),
          )
          as _i5.IGenericStore<_i2.ProposalData>);

  @override
  _i2.ISessions get sessions =>
      (super.noSuchMethod(
            Invocation.getter(#sessions),
            returnValue: _FakeISessions_4(this, Invocation.getter(#sessions)),
          )
          as _i2.ISessions);

  @override
  _i5.IGenericStore<_i2.SessionRequest> get pendingRequests =>
      (super.noSuchMethod(
            Invocation.getter(#pendingRequests),
            returnValue: _FakeIGenericStore_3<_i2.SessionRequest>(
              this,
              Invocation.getter(#pendingRequests),
            ),
          )
          as _i5.IGenericStore<_i2.SessionRequest>);

  @override
  _i5.IGenericStore<_i2.AuthPublicKey> get authKeys =>
      (super.noSuchMethod(
            Invocation.getter(#authKeys),
            returnValue: _FakeIGenericStore_3<_i2.AuthPublicKey>(
              this,
              Invocation.getter(#authKeys),
            ),
          )
          as _i5.IGenericStore<_i2.AuthPublicKey>);

  @override
  _i4.IPairingStore get pairings =>
      (super.noSuchMethod(
            Invocation.getter(#pairings),
            returnValue: _FakeIPairingStore_5(
              this,
              Invocation.getter(#pairings),
            ),
          )
          as _i4.IPairingStore);

  @override
  _i5.IGenericStore<String> get pairingTopics =>
      (super.noSuchMethod(
            Invocation.getter(#pairingTopics),
            returnValue: _FakeIGenericStore_3<String>(
              this,
              Invocation.getter(#pairingTopics),
            ),
          )
          as _i5.IGenericStore<String>);

  @override
  List<_i20.ExchangeAsset> getPaymentAssetsForNetwork({
    String? chainId,
    bool? includeNative = true,
    bool? includeTest = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentAssetsForNetwork, [], {
              #chainId: chainId,
              #includeNative: includeNative,
              #includeTest: includeTest,
            }),
            returnValue: <_i20.ExchangeAsset>[],
          )
          as List<_i20.ExchangeAsset>);

  @override
  _i21.Future<_i22.GetExchangesResult> getExchanges({
    required _i23.GetExchangesParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExchanges, [], {#params: params}),
            returnValue: _i21.Future<_i22.GetExchangesResult>.value(
              _i19.dummyValue<_i22.GetExchangesResult>(
                this,
                Invocation.method(#getExchanges, [], {#params: params}),
              ),
            ),
          )
          as _i21.Future<_i22.GetExchangesResult>);

  @override
  _i21.Future<_i22.GetExchangeUrlResult> getExchangeUrl({
    required _i23.GetExchangeUrlParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExchangeUrl, [], {#params: params}),
            returnValue: _i21.Future<_i22.GetExchangeUrlResult>.value(
              _i19.dummyValue<_i22.GetExchangeUrlResult>(
                this,
                Invocation.method(#getExchangeUrl, [], {#params: params}),
              ),
            ),
          )
          as _i21.Future<_i22.GetExchangeUrlResult>);

  @override
  _i21.Future<_i22.GetExchangeDepositStatusResult> getExchangeDepositStatus({
    required _i23.GetExchangeDepositStatusParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExchangeDepositStatus, [], {#params: params}),
            returnValue: _i21.Future<_i22.GetExchangeDepositStatusResult>.value(
              _i19.dummyValue<_i22.GetExchangeDepositStatusResult>(
                this,
                Invocation.method(#getExchangeDepositStatus, [], {
                  #params: params,
                }),
              ),
            ),
          )
          as _i21.Future<_i22.GetExchangeDepositStatusResult>);

  @override
  _i21.Future<_i2.ConnectResponse> connect({
    Map<String, _i2.RequiredNamespace>? requiredNamespaces,
    Map<String, _i2.RequiredNamespace>? optionalNamespaces,
    Map<String, String>? sessionProperties,
    String? pairingTopic,
    List<_i4.Relay>? relays,
    List<_i2.SessionAuthRequestParams>? authentication,
    List<List<String>>? methods,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [], {
              #requiredNamespaces: requiredNamespaces,
              #optionalNamespaces: optionalNamespaces,
              #sessionProperties: sessionProperties,
              #pairingTopic: pairingTopic,
              #relays: relays,
              #authentication: authentication,
              #methods: methods,
            }),
            returnValue: _i21.Future<_i2.ConnectResponse>.value(
              _FakeConnectResponse_6(
                this,
                Invocation.method(#connect, [], {
                  #requiredNamespaces: requiredNamespaces,
                  #optionalNamespaces: optionalNamespaces,
                  #sessionProperties: sessionProperties,
                  #pairingTopic: pairingTopic,
                  #relays: relays,
                  #authentication: authentication,
                  #methods: methods,
                }),
              ),
            ),
          )
          as _i21.Future<_i2.ConnectResponse>);

  @override
  _i21.Future<dynamic> request({
    int? requestId,
    required String? topic,
    required String? chainId,
    required _i2.SessionRequestParams? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#request, [], {
              #requestId: requestId,
              #topic: topic,
              #chainId: chainId,
              #request: request,
            }),
            returnValue: _i21.Future<dynamic>.value(),
          )
          as _i21.Future<dynamic>);

  @override
  void registerEventHandler({
    required String? chainId,
    required String? event,
    dynamic Function(String, dynamic)? handler,
  }) => super.noSuchMethod(
    Invocation.method(#registerEventHandler, [], {
      #chainId: chainId,
      #event: event,
      #handler: handler,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i21.Future<void> ping({required String? topic}) =>
      (super.noSuchMethod(
            Invocation.method(#ping, [], {#topic: topic}),
            returnValue: _i21.Future<void>.value(),
            returnValueForMissingStub: _i21.Future<void>.value(),
          )
          as _i21.Future<void>);

  @override
  _i21.Future<_i2.SessionAuthRequestResponse> authenticate({
    required _i2.SessionAuthRequestParams? params,
    String? walletUniversalLink,
    String? pairingTopic,
    List<List<String>>? methods,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {
              #params: params,
              #walletUniversalLink: walletUniversalLink,
              #pairingTopic: pairingTopic,
              #methods: methods,
            }),
            returnValue: _i21.Future<_i2.SessionAuthRequestResponse>.value(
              _FakeSessionAuthRequestResponse_7(
                this,
                Invocation.method(#authenticate, [], {
                  #params: params,
                  #walletUniversalLink: walletUniversalLink,
                  #pairingTopic: pairingTopic,
                  #methods: methods,
                }),
              ),
            ),
          )
          as _i21.Future<_i2.SessionAuthRequestResponse>);

  @override
  _i21.Future<bool> redirectToWallet({
    required String? topic,
    required _i4.Redirect? redirect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#redirectToWallet, [], {
              #topic: topic,
              #redirect: redirect,
            }),
            returnValue: _i21.Future<bool>.value(false),
          )
          as _i21.Future<bool>);

  @override
  _i21.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i21.Future<void>.value(),
            returnValueForMissingStub: _i21.Future<void>.value(),
          )
          as _i21.Future<void>);

  @override
  _i21.Future<void> disconnectSession({
    required String? topic,
    required _i2.ReownSignError? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectSession, [], {
              #topic: topic,
              #reason: reason,
            }),
            returnValue: _i21.Future<void>.value(),
            returnValueForMissingStub: _i21.Future<void>.value(),
          )
          as _i21.Future<void>);

  @override
  Map<String, _i2.SessionData> getActiveSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSessions, []),
            returnValue: <String, _i2.SessionData>{},
          )
          as Map<String, _i2.SessionData>);

  @override
  Map<String, _i2.SessionData> getSessionsForPairing({
    required String? pairingTopic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionsForPairing, [], {
              #pairingTopic: pairingTopic,
            }),
            returnValue: <String, _i2.SessionData>{},
          )
          as Map<String, _i2.SessionData>);

  @override
  Map<String, _i2.ProposalData> getPendingSessionProposals() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSessionProposals, []),
            returnValue: <String, _i2.ProposalData>{},
          )
          as Map<String, _i2.ProposalData>);

  @override
  String formatAuthMessage({
    required String? iss,
    required _i2.CacaoRequestPayload? cacaoPayload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#formatAuthMessage, [], {
              #iss: iss,
              #cacaoPayload: cacaoPayload,
            }),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.method(#formatAuthMessage, [], {
                #iss: iss,
                #cacaoPayload: cacaoPayload,
              }),
            ),
          )
          as String);

  @override
  _i21.Future<bool> validateSignedCacao({
    required _i2.Cacao? cacao,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#validateSignedCacao, [], {
              #cacao: cacao,
              #projectId: projectId,
            }),
            returnValue: _i21.Future<bool>.value(false),
          )
          as _i21.Future<bool>);

  @override
  _i21.Future<void> dispatchEnvelope(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#dispatchEnvelope, [url]),
            returnValue: _i21.Future<void>.value(),
            returnValueForMissingStub: _i21.Future<void>.value(),
          )
          as _i21.Future<void>);
}

/// A class which mocks [ITransfersService].
///
/// See the documentation for Mockito's code generation for more information.
class MockITransfersService extends _i1.Mock implements _i24.ITransfersService {
  MockITransfersService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i21.Future<_i25.GetQuoteStatusResult> getQuoteStatus({
    required _i26.GetQuoteStatusParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getQuoteStatus, [], {#params: params}),
            returnValue: _i21.Future<_i25.GetQuoteStatusResult>.value(
              _i19.dummyValue<_i25.GetQuoteStatusResult>(
                this,
                Invocation.method(#getQuoteStatus, [], {#params: params}),
              ),
            ),
          )
          as _i21.Future<_i25.GetQuoteStatusResult>);

  @override
  _i21.Future<_i27.Quote> getQuote({required _i26.GetQuoteParams? params}) =>
      (super.noSuchMethod(
            Invocation.method(#getQuote, [], {#params: params}),
            returnValue: _i21.Future<_i27.Quote>.value(
              _i19.dummyValue<_i27.Quote>(
                this,
                Invocation.method(#getQuote, [], {#params: params}),
              ),
            ),
          )
          as _i21.Future<_i27.Quote>);

  @override
  _i21.Future<_i25.GetExchangeAssetsResult> getExchangeAssets({
    required String? exchange,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExchangeAssets, [], {#exchange: exchange}),
            returnValue: _i21.Future<_i25.GetExchangeAssetsResult>.value(
              _i19.dummyValue<_i25.GetExchangeAssetsResult>(
                this,
                Invocation.method(#getExchangeAssets, [], {
                  #exchange: exchange,
                }),
              ),
            ),
          )
          as _i21.Future<_i25.GetExchangeAssetsResult>);
}

/// A class which mocks [IReownCore].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReownCore extends _i1.Mock implements _i4.IReownCore {
  MockIReownCore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get protocol =>
      (super.noSuchMethod(
            Invocation.getter(#protocol),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#protocol),
            ),
          )
          as String);

  @override
  String get version =>
      (super.noSuchMethod(
            Invocation.getter(#version),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#version),
            ),
          )
          as String);

  @override
  String get relayUrl =>
      (super.noSuchMethod(
            Invocation.getter(#relayUrl),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#relayUrl),
            ),
          )
          as String);

  @override
  String get projectId =>
      (super.noSuchMethod(
            Invocation.getter(#projectId),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#projectId),
            ),
          )
          as String);

  @override
  String get pushUrl =>
      (super.noSuchMethod(
            Invocation.getter(#pushUrl),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#pushUrl),
            ),
          )
          as String);

  @override
  _i6.IHeartBeat get heartbeat =>
      (super.noSuchMethod(
            Invocation.getter(#heartbeat),
            returnValue: _FakeIHeartBeat_8(this, Invocation.getter(#heartbeat)),
          )
          as _i6.IHeartBeat);

  @override
  _i7.ICrypto get crypto =>
      (super.noSuchMethod(
            Invocation.getter(#crypto),
            returnValue: _FakeICrypto_9(this, Invocation.getter(#crypto)),
          )
          as _i7.ICrypto);

  @override
  _i8.IRelayClient get relayClient =>
      (super.noSuchMethod(
            Invocation.getter(#relayClient),
            returnValue: _FakeIRelayClient_10(
              this,
              Invocation.getter(#relayClient),
            ),
          )
          as _i8.IRelayClient);

  @override
  _i9.IStore<Map<String, dynamic>> get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeIStore_11<Map<String, dynamic>>(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i9.IStore<Map<String, dynamic>>);

  @override
  _i9.IStore<Map<String, dynamic>> get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeIStore_11<Map<String, dynamic>>(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i9.IStore<Map<String, dynamic>>);

  @override
  _i10.IConnectivity get connectivity =>
      (super.noSuchMethod(
            Invocation.getter(#connectivity),
            returnValue: _FakeIConnectivity_12(
              this,
              Invocation.getter(#connectivity),
            ),
          )
          as _i10.IConnectivity);

  @override
  _i11.IExpirer get expirer =>
      (super.noSuchMethod(
            Invocation.getter(#expirer),
            returnValue: _FakeIExpirer_13(this, Invocation.getter(#expirer)),
          )
          as _i11.IExpirer);

  @override
  _i12.IPairing get pairing =>
      (super.noSuchMethod(
            Invocation.getter(#pairing),
            returnValue: _FakeIPairing_14(this, Invocation.getter(#pairing)),
          )
          as _i12.IPairing);

  @override
  _i13.IEcho get echo =>
      (super.noSuchMethod(
            Invocation.getter(#echo),
            returnValue: _FakeIEcho_15(this, Invocation.getter(#echo)),
          )
          as _i13.IEcho);

  @override
  _i14.IEvents get events =>
      (super.noSuchMethod(
            Invocation.getter(#events),
            returnValue: _FakeIEvents_16(this, Invocation.getter(#events)),
          )
          as _i14.IEvents);

  @override
  _i15.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_17(this, Invocation.getter(#logger)),
          )
          as _i15.Logger);

  @override
  _i16.IVerify get verify =>
      (super.noSuchMethod(
            Invocation.getter(#verify),
            returnValue: _FakeIVerify_18(this, Invocation.getter(#verify)),
          )
          as _i16.IVerify);

  @override
  _i17.ILinkModeStore get linkModeStore =>
      (super.noSuchMethod(
            Invocation.getter(#linkModeStore),
            returnValue: _FakeILinkModeStore_19(
              this,
              Invocation.getter(#linkModeStore),
            ),
          )
          as _i17.ILinkModeStore);

  @override
  set relayUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#relayUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  set heartbeat(_i6.IHeartBeat? value) => super.noSuchMethod(
    Invocation.setter(#heartbeat, value),
    returnValueForMissingStub: null,
  );

  @override
  set crypto(_i7.ICrypto? value) => super.noSuchMethod(
    Invocation.setter(#crypto, value),
    returnValueForMissingStub: null,
  );

  @override
  set relayClient(_i8.IRelayClient? value) => super.noSuchMethod(
    Invocation.setter(#relayClient, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i9.IStore<Map<String, dynamic>>? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set secureStorage(_i9.IStore<Map<String, dynamic>>? value) =>
      super.noSuchMethod(
        Invocation.setter(#secureStorage, value),
        returnValueForMissingStub: null,
      );

  @override
  set connectivity(_i10.IConnectivity? value) => super.noSuchMethod(
    Invocation.setter(#connectivity, value),
    returnValueForMissingStub: null,
  );

  @override
  set expirer(_i11.IExpirer? value) => super.noSuchMethod(
    Invocation.setter(#expirer, value),
    returnValueForMissingStub: null,
  );

  @override
  set pairing(_i12.IPairing? value) => super.noSuchMethod(
    Invocation.setter(#pairing, value),
    returnValueForMissingStub: null,
  );

  @override
  set echo(_i13.IEcho? value) => super.noSuchMethod(
    Invocation.setter(#echo, value),
    returnValueForMissingStub: null,
  );

  @override
  set events(_i14.IEvents? value) => super.noSuchMethod(
    Invocation.setter(#events, value),
    returnValueForMissingStub: null,
  );

  @override
  set verify(_i16.IVerify? value) => super.noSuchMethod(
    Invocation.setter(#verify, value),
    returnValueForMissingStub: null,
  );

  @override
  set linkModeStore(_i17.ILinkModeStore? value) => super.noSuchMethod(
    Invocation.setter(#linkModeStore, value),
    returnValueForMissingStub: null,
  );

  @override
  _i21.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i21.Future<void>.value(),
            returnValueForMissingStub: _i21.Future<void>.value(),
          )
          as _i21.Future<void>);

  @override
  void confirmOnlineStateOrThrow() => super.noSuchMethod(
    Invocation.method(#confirmOnlineStateOrThrow, []),
    returnValueForMissingStub: null,
  );

  @override
  _i21.Future<bool> addLinkModeSupportedApp(String? universalLink) =>
      (super.noSuchMethod(
            Invocation.method(#addLinkModeSupportedApp, [universalLink]),
            returnValue: _i21.Future<bool>.value(false),
          )
          as _i21.Future<bool>);

  @override
  List<String> getLinkModeSupportedApps() =>
      (super.noSuchMethod(
            Invocation.method(#getLinkModeSupportedApps, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  void addLogListener(dynamic Function(String)? callback) => super.noSuchMethod(
    Invocation.method(#addLogListener, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  bool removeLogListener(dynamic Function(String)? callback) =>
      (super.noSuchMethod(
            Invocation.method(#removeLogListener, [callback]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i15.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i21.Future<void> get init =>
      (super.noSuchMethod(
            Invocation.getter(#init),
            returnValue: _i21.Future<void>.value(),
          )
          as _i21.Future<void>);

  @override
  void v(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #v,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void t(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #t,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void d(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #d,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void i(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #i,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void w(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #w,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void e(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #e,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void wtf(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #wtf,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void f(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #f,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void log(
    _i15.Level? level,
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #log,
      [level, message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool isClosed() =>
      (super.noSuchMethod(Invocation.method(#isClosed, []), returnValue: false)
          as bool);

  @override
  _i21.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i21.Future<void>.value(),
            returnValueForMissingStub: _i21.Future<void>.value(),
          )
          as _i21.Future<void>);
}
