name: ci
description: Set up environment

inputs:
  platform:
    description: Platform where to run tests (ios/android)
    required: false
    default: 'android'

runs:
  using: composite
  steps:
    # Install Java 17
    - name: Install Java 17
      if: github.event.inputs.platform == 'android'
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        architecture: x86_64
        cache: 'gradle'

    # Cache Gradle
    - name: Cache Gradle
      if: github.event.inputs.platform == 'android'
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Install Flutter SDK
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'

    # Get package dependencies for dapp and generate files
    - name: Get package dependencies for dapp and generate files
      shell: bash
      working-directory: packages/reown_appkit/example/base
      run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          dart pub add polkadart_cli
          dart run polkadart_cli:generate -v
          dart format --output=none --set-exit-if-changed .
    
    # Get package dependencies for wallet and generate files
    - name: Get package dependencies for wallet and generate files
      shell: bash
      working-directory: packages/reown_walletkit/example
      run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          dart format --output=none --set-exit-if-changed .

    # Cache Flutter dependencies
    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          **/build
          **/.dart_tool
          **/.pub-cache
          **/.pub
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
