name: ci
description: Installs dependencies

runs:
  using: composite
  steps:
    # Install Flutter SDK
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'

    # Get package dependencies for dapp and generate files
    - name: Get package dependencies for dapp and generate files
      shell: bash
      working-directory: packages/reown_appkit/example/base
      run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          dart format --output=none --set-exit-if-changed .
    
    # Get package dependencies for wallet and generate files
    - name: Get package dependencies for wallet and generate files
      shell: bash
      working-directory: packages/reown_walletkit/example
      run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          dart format --output=none --set-exit-if-changed .

    # add flutter analyze when packages are published
