name: ci
description: Installs dependencies

inputs:
  working-directory:
    description: 'Package directory'
    required: true

runs:
  using: composite
  steps:
    # Install Flutter SDK
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'

    # Get package dependencies and generate files
    - name: Get package dependencies and generate files
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          dart format --output=none --set-exit-if-changed .
    # add flutter analyze when packages are published

    