// Mocks generated by Mockito 5.4.4 from annotations
// in reown_core/test/shared/shared_test_utils.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i28;
import 'dart:typed_data' as _i26;

import 'package:event/event.dart' as _i9;
import 'package:http/http.dart' as _i10;
import 'package:logger/logger.dart' as _i22;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i27;
import 'package:reown_core/connectivity/i_connectivity.dart' as _i19;
import 'package:reown_core/core_impl.dart' as _i33;
import 'package:reown_core/crypto/crypto.dart' as _i29;
import 'package:reown_core/crypto/crypto_models.dart' as _i2;
import 'package:reown_core/crypto/crypto_utils.dart' as _i25;
import 'package:reown_core/crypto/i_crypto.dart' as _i11;
import 'package:reown_core/crypto/i_crypto_utils.dart' as _i5;
import 'package:reown_core/echo/i_echo.dart' as _i15;
import 'package:reown_core/events/i_events.dart' as _i16;
import 'package:reown_core/heartbit/i_heartbeat.dart' as _i17;
import 'package:reown_core/i_core_impl.dart' as _i3;
import 'package:reown_core/models/basic_models.dart' as _i38;
import 'package:reown_core/pairing/i_expirer.dart' as _i13;
import 'package:reown_core/pairing/i_pairing.dart' as _i14;
import 'package:reown_core/relay_auth/i_relay_auth.dart' as _i6;
import 'package:reown_core/relay_auth/relay_auth_models.dart' as _i7;
import 'package:reown_core/relay_client/i_message_tracker.dart' as _i23;
import 'package:reown_core/relay_client/i_relay_client.dart' as _i12;
import 'package:reown_core/relay_client/json_rpc_2/src/peer.dart' as _i37;
import 'package:reown_core/relay_client/message_tracker.dart' as _i30;
import 'package:reown_core/relay_client/relay_client.dart' as _i35;
import 'package:reown_core/relay_client/relay_client_models.dart' as _i36;
import 'package:reown_core/relay_client/websocket/http_client.dart' as _i32;
import 'package:reown_core/relay_client/websocket/i_websocket_handler.dart'
    as _i24;
import 'package:reown_core/relay_client/websocket/websocket_handler.dart'
    as _i34;
import 'package:reown_core/store/i_generic_store.dart' as _i4;
import 'package:reown_core/store/i_store.dart' as _i8;
import 'package:reown_core/store/link_mode_store.dart' as _i20;
import 'package:reown_core/store/store_models.dart' as _i31;
import 'package:reown_core/verify/i_verify.dart' as _i18;
import 'package:reown_core/yttrium/i_rust_sign_client.dart' as _i21;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCryptoKeyPair_0 extends _i1.SmartFake implements _i2.CryptoKeyPair {
  _FakeCryptoKeyPair_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEncodingParams_1 extends _i1.SmartFake
    implements _i2.EncodingParams {
  _FakeEncodingParams_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEncodingValidation_2 extends _i1.SmartFake
    implements _i2.EncodingValidation {
  _FakeEncodingValidation_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIReownCore_3 extends _i1.SmartFake implements _i3.IReownCore {
  _FakeIReownCore_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIGenericStore_4<T> extends _i1.SmartFake
    implements _i4.IGenericStore<T> {
  _FakeIGenericStore_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeICryptoUtils_5 extends _i1.SmartFake implements _i5.ICryptoUtils {
  _FakeICryptoUtils_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIRelayAuth_6 extends _i1.SmartFake implements _i6.IRelayAuth {
  _FakeIRelayAuth_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRelayAuthKeyPair_7 extends _i1.SmartFake
    implements _i7.RelayAuthKeyPair {
  _FakeRelayAuthKeyPair_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIStore_8<T> extends _i1.SmartFake implements _i8.IStore<T> {
  _FakeIStore_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEvent_9<T extends _i9.EventArgs> extends _i1.SmartFake
    implements _i9.Event<T> {
  _FakeEvent_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_10 extends _i1.SmartFake implements _i10.Response {
  _FakeResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeICrypto_11 extends _i1.SmartFake implements _i11.ICrypto {
  _FakeICrypto_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIRelayClient_12 extends _i1.SmartFake implements _i12.IRelayClient {
  _FakeIRelayClient_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIExpirer_13 extends _i1.SmartFake implements _i13.IExpirer {
  _FakeIExpirer_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIPairing_14 extends _i1.SmartFake implements _i14.IPairing {
  _FakeIPairing_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIEcho_15 extends _i1.SmartFake implements _i15.IEcho {
  _FakeIEcho_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIEvents_16 extends _i1.SmartFake implements _i16.IEvents {
  _FakeIEvents_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIHeartBeat_17 extends _i1.SmartFake implements _i17.IHeartBeat {
  _FakeIHeartBeat_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIVerify_18 extends _i1.SmartFake implements _i18.IVerify {
  _FakeIVerify_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIConnectivity_19 extends _i1.SmartFake
    implements _i19.IConnectivity {
  _FakeIConnectivity_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeILinkModeStore_20 extends _i1.SmartFake
    implements _i20.ILinkModeStore {
  _FakeILinkModeStore_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIRustSignClient_21 extends _i1.SmartFake
    implements _i21.IRustSignClient {
  _FakeIRustSignClient_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogger_22 extends _i1.SmartFake implements _i22.Logger {
  _FakeLogger_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIMessageTracker_23 extends _i1.SmartFake
    implements _i23.IMessageTracker {
  _FakeIMessageTracker_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIWebSocketHandler_24 extends _i1.SmartFake
    implements _i24.IWebSocketHandler {
  _FakeIWebSocketHandler_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CryptoUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockCryptoUtils extends _i1.Mock implements _i25.CryptoUtils {
  MockCryptoUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CryptoKeyPair generateKeyPair() => (super.noSuchMethod(
        Invocation.method(
          #generateKeyPair,
          [],
        ),
        returnValue: _FakeCryptoKeyPair_0(
          this,
          Invocation.method(
            #generateKeyPair,
            [],
          ),
        ),
      ) as _i2.CryptoKeyPair);

  @override
  _i26.Uint8List randomBytes(int? length) => (super.noSuchMethod(
        Invocation.method(
          #randomBytes,
          [length],
        ),
        returnValue: _i26.Uint8List(0),
      ) as _i26.Uint8List);

  @override
  String generateRandomBytes32() => (super.noSuchMethod(
        Invocation.method(
          #generateRandomBytes32,
          [],
        ),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.method(
            #generateRandomBytes32,
            [],
          ),
        ),
      ) as String);

  @override
  _i28.Future<String> deriveSymKey(
    String? privKeyA,
    String? pubKeyB,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deriveSymKey,
          [
            privKeyA,
            pubKeyB,
          ],
        ),
        returnValue: _i28.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #deriveSymKey,
            [
              privKeyA,
              pubKeyB,
            ],
          ),
        )),
      ) as _i28.Future<String>);

  @override
  String hashKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #hashKey,
          [key],
        ),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.method(
            #hashKey,
            [key],
          ),
        ),
      ) as String);

  @override
  String hashMessage(String? message) => (super.noSuchMethod(
        Invocation.method(
          #hashMessage,
          [message],
        ),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.method(
            #hashMessage,
            [message],
          ),
        ),
      ) as String);

  @override
  _i28.Future<String> encrypt(
    String? message,
    String? symKey, {
    int? type,
    String? iv,
    String? senderPublicKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #encrypt,
          [
            message,
            symKey,
          ],
          {
            #type: type,
            #iv: iv,
            #senderPublicKey: senderPublicKey,
          },
        ),
        returnValue: _i28.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #encrypt,
            [
              message,
              symKey,
            ],
            {
              #type: type,
              #iv: iv,
              #senderPublicKey: senderPublicKey,
            },
          ),
        )),
      ) as _i28.Future<String>);

  @override
  _i28.Future<String> decrypt(
    String? symKey,
    String? encoded,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #decrypt,
          [
            symKey,
            encoded,
          ],
        ),
        returnValue: _i28.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #decrypt,
            [
              symKey,
              encoded,
            ],
          ),
        )),
      ) as _i28.Future<String>);

  @override
  String serialize(
    int? type,
    _i26.Uint8List? sealed,
    _i26.Uint8List? iv, {
    _i26.Uint8List? senderPublicKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #serialize,
          [
            type,
            sealed,
            iv,
          ],
          {#senderPublicKey: senderPublicKey},
        ),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.method(
            #serialize,
            [
              type,
              sealed,
              iv,
            ],
            {#senderPublicKey: senderPublicKey},
          ),
        ),
      ) as String);

  @override
  _i2.EncodingParams deserialize(String? encoded) => (super.noSuchMethod(
        Invocation.method(
          #deserialize,
          [encoded],
        ),
        returnValue: _FakeEncodingParams_1(
          this,
          Invocation.method(
            #deserialize,
            [encoded],
          ),
        ),
      ) as _i2.EncodingParams);

  @override
  _i2.EncodingValidation validateDecoding(
    String? encoded, {
    String? receiverPublicKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateDecoding,
          [encoded],
          {#receiverPublicKey: receiverPublicKey},
        ),
        returnValue: _FakeEncodingValidation_2(
          this,
          Invocation.method(
            #validateDecoding,
            [encoded],
            {#receiverPublicKey: receiverPublicKey},
          ),
        ),
      ) as _i2.EncodingValidation);

  @override
  _i2.EncodingValidation validateEncoding({
    int? type,
    String? senderPublicKey,
    String? receiverPublicKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateEncoding,
          [],
          {
            #type: type,
            #senderPublicKey: senderPublicKey,
            #receiverPublicKey: receiverPublicKey,
          },
        ),
        returnValue: _FakeEncodingValidation_2(
          this,
          Invocation.method(
            #validateEncoding,
            [],
            {
              #type: type,
              #senderPublicKey: senderPublicKey,
              #receiverPublicKey: receiverPublicKey,
            },
          ),
        ),
      ) as _i2.EncodingValidation);

  @override
  bool isTypeOneEnvelope(_i2.EncodingValidation? result) => (super.noSuchMethod(
        Invocation.method(
          #isTypeOneEnvelope,
          [result],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isTypeTwoEnvelope(_i2.EncodingValidation? result) => (super.noSuchMethod(
        Invocation.method(
          #isTypeTwoEnvelope,
          [result],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i26.Uint8List encodeTypeByte(int? type) => (super.noSuchMethod(
        Invocation.method(
          #encodeTypeByte,
          [type],
        ),
        returnValue: _i26.Uint8List(0),
      ) as _i26.Uint8List);

  @override
  int decodeTypeByte(_i26.Uint8List? byte) => (super.noSuchMethod(
        Invocation.method(
          #decodeTypeByte,
          [byte],
        ),
        returnValue: 0,
      ) as int);

  @override
  String encodeTypeTwoEnvelope({required String? message}) =>
      (super.noSuchMethod(
        Invocation.method(
          #encodeTypeTwoEnvelope,
          [],
          {#message: message},
        ),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.method(
            #encodeTypeTwoEnvelope,
            [],
            {#message: message},
          ),
        ),
      ) as String);

  @override
  String decodeTypeTwoEnvelope({required String? message}) =>
      (super.noSuchMethod(
        Invocation.method(
          #decodeTypeTwoEnvelope,
          [],
          {#message: message},
        ),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.method(
            #decodeTypeTwoEnvelope,
            [],
            {#message: message},
          ),
        ),
      ) as String);
}

/// A class which mocks [Crypto].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrypto extends _i1.Mock implements _i29.Crypto {
  MockCrypto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.IReownCore get core => (super.noSuchMethod(
        Invocation.getter(#core),
        returnValue: _FakeIReownCore_3(
          this,
          Invocation.getter(#core),
        ),
      ) as _i3.IReownCore);

  @override
  _i4.IGenericStore<String> get keyChain => (super.noSuchMethod(
        Invocation.getter(#keyChain),
        returnValue: _FakeIGenericStore_4<String>(
          this,
          Invocation.getter(#keyChain),
        ),
      ) as _i4.IGenericStore<String>);

  @override
  set keyChain(_i4.IGenericStore<String>? _keyChain) => super.noSuchMethod(
        Invocation.setter(
          #keyChain,
          _keyChain,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.ICryptoUtils get utils => (super.noSuchMethod(
        Invocation.getter(#utils),
        returnValue: _FakeICryptoUtils_5(
          this,
          Invocation.getter(#utils),
        ),
      ) as _i5.ICryptoUtils);

  @override
  set utils(_i5.ICryptoUtils? _utils) => super.noSuchMethod(
        Invocation.setter(
          #utils,
          _utils,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.IRelayAuth get relayAuth => (super.noSuchMethod(
        Invocation.getter(#relayAuth),
        returnValue: _FakeIRelayAuth_6(
          this,
          Invocation.getter(#relayAuth),
        ),
      ) as _i6.IRelayAuth);

  @override
  set relayAuth(_i6.IRelayAuth? _relayAuth) => super.noSuchMethod(
        Invocation.setter(
          #relayAuth,
          _relayAuth,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i28.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  bool hasKeys(String? tag) => (super.noSuchMethod(
        Invocation.method(
          #hasKeys,
          [tag],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i28.Future<String> getClientId() => (super.noSuchMethod(
        Invocation.method(
          #getClientId,
          [],
        ),
        returnValue: _i28.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #getClientId,
            [],
          ),
        )),
      ) as _i28.Future<String>);

  @override
  _i28.Future<_i7.RelayAuthKeyPair> getClientKeyPair() => (super.noSuchMethod(
        Invocation.method(
          #getClientKeyPair,
          [],
        ),
        returnValue:
            _i28.Future<_i7.RelayAuthKeyPair>.value(_FakeRelayAuthKeyPair_7(
          this,
          Invocation.method(
            #getClientKeyPair,
            [],
          ),
        )),
      ) as _i28.Future<_i7.RelayAuthKeyPair>);

  @override
  _i28.Future<String> generateKeyPair() => (super.noSuchMethod(
        Invocation.method(
          #generateKeyPair,
          [],
        ),
        returnValue: _i28.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #generateKeyPair,
            [],
          ),
        )),
      ) as _i28.Future<String>);

  @override
  _i28.Future<String> generateSharedKey(
    String? selfPublicKey,
    String? peerPublicKey, {
    String? overrideTopic,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSharedKey,
          [
            selfPublicKey,
            peerPublicKey,
          ],
          {#overrideTopic: overrideTopic},
        ),
        returnValue: _i28.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #generateSharedKey,
            [
              selfPublicKey,
              peerPublicKey,
            ],
            {#overrideTopic: overrideTopic},
          ),
        )),
      ) as _i28.Future<String>);

  @override
  _i28.Future<String> setSymKey(
    String? symKey, {
    String? overrideTopic,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSymKey,
          [symKey],
          {#overrideTopic: overrideTopic},
        ),
        returnValue: _i28.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #setSymKey,
            [symKey],
            {#overrideTopic: overrideTopic},
          ),
        )),
      ) as _i28.Future<String>);

  @override
  String? getSymKey(String? topic) => (super.noSuchMethod(Invocation.method(
        #getSymKey,
        [topic],
      )) as String?);

  @override
  _i28.Future<void> deleteKeyPair(String? publicKey) => (super.noSuchMethod(
        Invocation.method(
          #deleteKeyPair,
          [publicKey],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<void> deleteSymKey(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #deleteSymKey,
          [topic],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<String?> encode(
    String? topic,
    Map<String, dynamic>? payload, {
    _i2.EncodeOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #encode,
          [
            topic,
            payload,
          ],
          {#options: options},
        ),
        returnValue: _i28.Future<String?>.value(),
      ) as _i28.Future<String?>);

  @override
  _i28.Future<String?> decode(
    String? topic,
    String? encoded, {
    _i2.DecodeOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decode,
          [
            topic,
            encoded,
          ],
          {#options: options},
        ),
        returnValue: _i28.Future<String?>.value(),
      ) as _i28.Future<String?>);

  @override
  _i28.Future<String> signJWT(String? aud) => (super.noSuchMethod(
        Invocation.method(
          #signJWT,
          [aud],
        ),
        returnValue: _i28.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #signJWT,
            [aud],
          ),
        )),
      ) as _i28.Future<String>);

  @override
  int getPayloadType(String? encoded) => (super.noSuchMethod(
        Invocation.method(
          #getPayloadType,
          [encoded],
        ),
        returnValue: 0,
      ) as int);

  @override
  String? getPayloadSenderPublicKey(String? encoded) =>
      (super.noSuchMethod(Invocation.method(
        #getPayloadSenderPublicKey,
        [encoded],
      )) as String?);

  @override
  _i5.ICryptoUtils getUtils() => (super.noSuchMethod(
        Invocation.method(
          #getUtils,
          [],
        ),
        returnValue: _FakeICryptoUtils_5(
          this,
          Invocation.method(
            #getUtils,
            [],
          ),
        ),
      ) as _i5.ICryptoUtils);
}

/// A class which mocks [MessageTracker].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageTracker extends _i1.Mock implements _i30.MessageTracker {
  MockMessageTracker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#context),
        ),
      ) as String);

  @override
  String get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#version),
        ),
      ) as String);

  @override
  _i8.IStore<dynamic> get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeIStore_8<dynamic>(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i8.IStore<dynamic>);

  @override
  _i9.Event<_i31.StoreCreateEvent<Map<String, String>>> get onCreate =>
      (super.noSuchMethod(
        Invocation.getter(#onCreate),
        returnValue: _FakeEvent_9<_i31.StoreCreateEvent<Map<String, String>>>(
          this,
          Invocation.getter(#onCreate),
        ),
      ) as _i9.Event<_i31.StoreCreateEvent<Map<String, String>>>);

  @override
  _i9.Event<_i31.StoreUpdateEvent<Map<String, String>>> get onUpdate =>
      (super.noSuchMethod(
        Invocation.getter(#onUpdate),
        returnValue: _FakeEvent_9<_i31.StoreUpdateEvent<Map<String, String>>>(
          this,
          Invocation.getter(#onUpdate),
        ),
      ) as _i9.Event<_i31.StoreUpdateEvent<Map<String, String>>>);

  @override
  _i9.Event<_i31.StoreDeleteEvent<Map<String, String>>> get onDelete =>
      (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeEvent_9<_i31.StoreDeleteEvent<Map<String, String>>>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i9.Event<_i31.StoreDeleteEvent<Map<String, String>>>);

  @override
  _i9.Event<_i31.StoreErrorEvent<Map<String, String>>> get onError =>
      (super.noSuchMethod(
        Invocation.getter(#onError),
        returnValue: _FakeEvent_9<_i31.StoreErrorEvent<Map<String, String>>>(
          this,
          Invocation.getter(#onError),
        ),
      ) as _i9.Event<_i31.StoreErrorEvent<Map<String, String>>>);

  @override
  _i9.Event<_i31.StoreSyncEvent> get onSync => (super.noSuchMethod(
        Invocation.getter(#onSync),
        returnValue: _FakeEvent_9<_i31.StoreSyncEvent>(
          this,
          Invocation.getter(#onSync),
        ),
      ) as _i9.Event<_i31.StoreSyncEvent>);

  @override
  Map<String, Map<String, String>> get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: <String, Map<String, String>>{},
      ) as Map<String, Map<String, String>>);

  @override
  set data(Map<String, Map<String, String>>? _data) => super.noSuchMethod(
        Invocation.setter(
          #data,
          _data,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, String> Function(dynamic) get fromJson => (super.noSuchMethod(
        Invocation.getter(#fromJson),
        returnValue: (dynamic __p0) => <String, String>{},
      ) as Map<String, String> Function(dynamic));

  @override
  String get storageKey => (super.noSuchMethod(
        Invocation.getter(#storageKey),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#storageKey),
        ),
      ) as String);

  @override
  String hashMessage(String? message) => (super.noSuchMethod(
        Invocation.method(
          #hashMessage,
          [message],
        ),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.method(
            #hashMessage,
            [message],
          ),
        ),
      ) as String);

  @override
  _i28.Future<void> recordMessageEvent(
    String? topic,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordMessageEvent,
          [
            topic,
            message,
          ],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  bool messageIsRecorded(
    String? topic,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #messageIsRecorded,
          [
            topic,
            message,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i28.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  bool has(String? key) => (super.noSuchMethod(
        Invocation.method(
          #has,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, String>? get(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Map<String, String>?);

  @override
  List<Map<String, String>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <Map<String, String>>[],
      ) as List<Map<String, String>>);

  @override
  _i28.Future<void> set(
    String? key,
    Map<String, String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            key,
            value,
          ],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<void> persist() => (super.noSuchMethod(
        Invocation.method(
          #persist,
          [],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<void> restore() => (super.noSuchMethod(
        Invocation.method(
          #restore,
          [],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  void checkInitialized() => super.noSuchMethod(
        Invocation.method(
          #checkInitialized,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HttpWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpWrapper extends _i1.Mock implements _i32.HttpWrapper {
  MockHttpWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i28.Future<_i10.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i28.Future<_i10.Response>.value(_FakeResponse_10(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i28.Future<_i10.Response>);

  @override
  _i28.Future<_i10.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {#headers: headers},
        ),
        returnValue: _i28.Future<_i10.Response>.value(_FakeResponse_10(
          this,
          Invocation.method(
            #delete,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i28.Future<_i10.Response>);

  @override
  _i28.Future<_i10.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
          },
        ),
        returnValue: _i28.Future<_i10.Response>.value(_FakeResponse_10(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
            },
          ),
        )),
      ) as _i28.Future<_i10.Response>);
}

/// A class which mocks [ReownCore].
///
/// See the documentation for Mockito's code generation for more information.
class MockReownCore extends _i1.Mock implements _i33.ReownCore {
  MockReownCore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get projectId => (super.noSuchMethod(
        Invocation.getter(#projectId),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#projectId),
        ),
      ) as String);

  @override
  String get relayUrl => (super.noSuchMethod(
        Invocation.getter(#relayUrl),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#relayUrl),
        ),
      ) as String);

  @override
  set relayUrl(String? _relayUrl) => super.noSuchMethod(
        Invocation.setter(
          #relayUrl,
          _relayUrl,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get pushUrl => (super.noSuchMethod(
        Invocation.getter(#pushUrl),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#pushUrl),
        ),
      ) as String);

  @override
  set pushUrl(String? _pushUrl) => super.noSuchMethod(
        Invocation.setter(
          #pushUrl,
          _pushUrl,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.ICrypto get crypto => (super.noSuchMethod(
        Invocation.getter(#crypto),
        returnValue: _FakeICrypto_11(
          this,
          Invocation.getter(#crypto),
        ),
      ) as _i11.ICrypto);

  @override
  set crypto(_i11.ICrypto? _crypto) => super.noSuchMethod(
        Invocation.setter(
          #crypto,
          _crypto,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.IRelayClient get relayClient => (super.noSuchMethod(
        Invocation.getter(#relayClient),
        returnValue: _FakeIRelayClient_12(
          this,
          Invocation.getter(#relayClient),
        ),
      ) as _i12.IRelayClient);

  @override
  set relayClient(_i12.IRelayClient? _relayClient) => super.noSuchMethod(
        Invocation.setter(
          #relayClient,
          _relayClient,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.IExpirer get expirer => (super.noSuchMethod(
        Invocation.getter(#expirer),
        returnValue: _FakeIExpirer_13(
          this,
          Invocation.getter(#expirer),
        ),
      ) as _i13.IExpirer);

  @override
  set expirer(_i13.IExpirer? _expirer) => super.noSuchMethod(
        Invocation.setter(
          #expirer,
          _expirer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.IPairing get pairing => (super.noSuchMethod(
        Invocation.getter(#pairing),
        returnValue: _FakeIPairing_14(
          this,
          Invocation.getter(#pairing),
        ),
      ) as _i14.IPairing);

  @override
  set pairing(_i14.IPairing? _pairing) => super.noSuchMethod(
        Invocation.setter(
          #pairing,
          _pairing,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.IEcho get echo => (super.noSuchMethod(
        Invocation.getter(#echo),
        returnValue: _FakeIEcho_15(
          this,
          Invocation.getter(#echo),
        ),
      ) as _i15.IEcho);

  @override
  set echo(_i15.IEcho? _echo) => super.noSuchMethod(
        Invocation.setter(
          #echo,
          _echo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.IEvents get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _FakeIEvents_16(
          this,
          Invocation.getter(#events),
        ),
      ) as _i16.IEvents);

  @override
  set events(_i16.IEvents? _events) => super.noSuchMethod(
        Invocation.setter(
          #events,
          _events,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i17.IHeartBeat get heartbeat => (super.noSuchMethod(
        Invocation.getter(#heartbeat),
        returnValue: _FakeIHeartBeat_17(
          this,
          Invocation.getter(#heartbeat),
        ),
      ) as _i17.IHeartBeat);

  @override
  set heartbeat(_i17.IHeartBeat? _heartbeat) => super.noSuchMethod(
        Invocation.setter(
          #heartbeat,
          _heartbeat,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.IVerify get verify => (super.noSuchMethod(
        Invocation.getter(#verify),
        returnValue: _FakeIVerify_18(
          this,
          Invocation.getter(#verify),
        ),
      ) as _i18.IVerify);

  @override
  set verify(_i18.IVerify? _verify) => super.noSuchMethod(
        Invocation.setter(
          #verify,
          _verify,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.IConnectivity get connectivity => (super.noSuchMethod(
        Invocation.getter(#connectivity),
        returnValue: _FakeIConnectivity_19(
          this,
          Invocation.getter(#connectivity),
        ),
      ) as _i19.IConnectivity);

  @override
  set connectivity(_i19.IConnectivity? _connectivity) => super.noSuchMethod(
        Invocation.setter(
          #connectivity,
          _connectivity,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.ILinkModeStore get linkModeStore => (super.noSuchMethod(
        Invocation.getter(#linkModeStore),
        returnValue: _FakeILinkModeStore_20(
          this,
          Invocation.getter(#linkModeStore),
        ),
      ) as _i20.ILinkModeStore);

  @override
  set linkModeStore(_i20.ILinkModeStore? _linkModeStore) => super.noSuchMethod(
        Invocation.setter(
          #linkModeStore,
          _linkModeStore,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i21.IRustSignClient get rustSignClient => (super.noSuchMethod(
        Invocation.getter(#rustSignClient),
        returnValue: _FakeIRustSignClient_21(
          this,
          Invocation.getter(#rustSignClient),
        ),
      ) as _i21.IRustSignClient);

  @override
  set rustSignClient(_i21.IRustSignClient? _rustSignClient) =>
      super.noSuchMethod(
        Invocation.setter(
          #rustSignClient,
          _rustSignClient,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.IStore<Map<String, dynamic>> get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeIStore_8<Map<String, dynamic>>(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i8.IStore<Map<String, dynamic>>);

  @override
  set storage(_i8.IStore<Map<String, dynamic>>? _storage) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          _storage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get protocol => (super.noSuchMethod(
        Invocation.getter(#protocol),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#protocol),
        ),
      ) as String);

  @override
  String get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#version),
        ),
      ) as String);

  @override
  _i22.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_22(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i22.Logger);

  @override
  void addLogListener(dynamic Function(String)? callback) => super.noSuchMethod(
        Invocation.method(
          #addLogListener,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool removeLogListener(dynamic Function(String)? callback) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeLogListener,
          [callback],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i28.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<bool> addLinkModeSupportedApp(String? universalLink) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLinkModeSupportedApp,
          [universalLink],
        ),
        returnValue: _i28.Future<bool>.value(false),
      ) as _i28.Future<bool>);

  @override
  List<String> getLinkModeSupportedApps() => (super.noSuchMethod(
        Invocation.method(
          #getLinkModeSupportedApps,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void confirmOnlineStateOrThrow() => super.noSuchMethod(
        Invocation.method(
          #confirmOnlineStateOrThrow,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WebSocketHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketHandler extends _i1.Mock implements _i34.WebSocketHandler {
  MockWebSocketHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i28.Future<void> get ready => (super.noSuchMethod(
        Invocation.getter(#ready),
        returnValue: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<void> setup({required String? url}) => (super.noSuchMethod(
        Invocation.method(
          #setup,
          [],
          {#url: url},
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);
}

/// A class which mocks [RelayClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelayClient extends _i1.Mock implements _i35.RelayClient {
  MockRelayClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Event<_i9.EventArgs> get onRelayClientConnect => (super.noSuchMethod(
        Invocation.getter(#onRelayClientConnect),
        returnValue: _FakeEvent_9<_i9.EventArgs>(
          this,
          Invocation.getter(#onRelayClientConnect),
        ),
      ) as _i9.Event<_i9.EventArgs>);

  @override
  _i9.Event<_i9.EventArgs> get onRelayClientDisconnect => (super.noSuchMethod(
        Invocation.getter(#onRelayClientDisconnect),
        returnValue: _FakeEvent_9<_i9.EventArgs>(
          this,
          Invocation.getter(#onRelayClientDisconnect),
        ),
      ) as _i9.Event<_i9.EventArgs>);

  @override
  _i9.Event<_i36.ErrorEvent> get onRelayClientError => (super.noSuchMethod(
        Invocation.getter(#onRelayClientError),
        returnValue: _FakeEvent_9<_i36.ErrorEvent>(
          this,
          Invocation.getter(#onRelayClientError),
        ),
      ) as _i9.Event<_i36.ErrorEvent>);

  @override
  _i9.Event<_i36.MessageEvent> get onRelayClientMessage => (super.noSuchMethod(
        Invocation.getter(#onRelayClientMessage),
        returnValue: _FakeEvent_9<_i36.MessageEvent>(
          this,
          Invocation.getter(#onRelayClientMessage),
        ),
      ) as _i9.Event<_i36.MessageEvent>);

  @override
  _i9.Event<_i36.MessageEvent> get onLinkModeMessage => (super.noSuchMethod(
        Invocation.getter(#onLinkModeMessage),
        returnValue: _FakeEvent_9<_i36.MessageEvent>(
          this,
          Invocation.getter(#onLinkModeMessage),
        ),
      ) as _i9.Event<_i36.MessageEvent>);

  @override
  _i9.Event<_i36.SubscriptionEvent> get onSubscriptionCreated =>
      (super.noSuchMethod(
        Invocation.getter(#onSubscriptionCreated),
        returnValue: _FakeEvent_9<_i36.SubscriptionEvent>(
          this,
          Invocation.getter(#onSubscriptionCreated),
        ),
      ) as _i9.Event<_i36.SubscriptionEvent>);

  @override
  _i9.Event<_i36.SubscriptionDeletionEvent> get onSubscriptionDeleted =>
      (super.noSuchMethod(
        Invocation.getter(#onSubscriptionDeleted),
        returnValue: _FakeEvent_9<_i36.SubscriptionDeletionEvent>(
          this,
          Invocation.getter(#onSubscriptionDeleted),
        ),
      ) as _i9.Event<_i36.SubscriptionDeletionEvent>);

  @override
  _i9.Event<_i9.EventArgs> get onSubscriptionResubscribed =>
      (super.noSuchMethod(
        Invocation.getter(#onSubscriptionResubscribed),
        returnValue: _FakeEvent_9<_i9.EventArgs>(
          this,
          Invocation.getter(#onSubscriptionResubscribed),
        ),
      ) as _i9.Event<_i9.EventArgs>);

  @override
  _i9.Event<_i9.EventArgs> get onSubscriptionSync => (super.noSuchMethod(
        Invocation.getter(#onSubscriptionSync),
        returnValue: _FakeEvent_9<_i9.EventArgs>(
          this,
          Invocation.getter(#onSubscriptionSync),
        ),
      ) as _i9.Event<_i9.EventArgs>);

  @override
  set jsonRPC(_i37.Peer? _jsonRPC) => super.noSuchMethod(
        Invocation.setter(
          #jsonRPC,
          _jsonRPC,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, _i28.Future<dynamic>> get pendingSubscriptions =>
      (super.noSuchMethod(
        Invocation.getter(#pendingSubscriptions),
        returnValue: <String, _i28.Future<dynamic>>{},
      ) as Map<String, _i28.Future<dynamic>>);

  @override
  set pendingSubscriptions(
          Map<String, _i28.Future<dynamic>>? _pendingSubscriptions) =>
      super.noSuchMethod(
        Invocation.setter(
          #pendingSubscriptions,
          _pendingSubscriptions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i23.IMessageTracker get messageTracker => (super.noSuchMethod(
        Invocation.getter(#messageTracker),
        returnValue: _FakeIMessageTracker_23(
          this,
          Invocation.getter(#messageTracker),
        ),
      ) as _i23.IMessageTracker);

  @override
  set messageTracker(_i23.IMessageTracker? _messageTracker) =>
      super.noSuchMethod(
        Invocation.setter(
          #messageTracker,
          _messageTracker,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.IGenericStore<String> get topicMap => (super.noSuchMethod(
        Invocation.getter(#topicMap),
        returnValue: _FakeIGenericStore_4<String>(
          this,
          Invocation.getter(#topicMap),
        ),
      ) as _i4.IGenericStore<String>);

  @override
  set topicMap(_i4.IGenericStore<String>? _topicMap) => super.noSuchMethod(
        Invocation.setter(
          #topicMap,
          _topicMap,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i24.IWebSocketHandler get socketHandler => (super.noSuchMethod(
        Invocation.getter(#socketHandler),
        returnValue: _FakeIWebSocketHandler_24(
          this,
          Invocation.getter(#socketHandler),
        ),
      ) as _i24.IWebSocketHandler);

  @override
  _i3.IReownCore get core => (super.noSuchMethod(
        Invocation.getter(#core),
        returnValue: _FakeIReownCore_3(
          this,
          Invocation.getter(#core),
        ),
      ) as _i3.IReownCore);

  @override
  set core(_i3.IReownCore? _core) => super.noSuchMethod(
        Invocation.setter(
          #core,
          _core,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i28.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<void> publish({
    required String? topic,
    required String? message,
    required _i38.PublishOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publish,
          [],
          {
            #topic: topic,
            #message: message,
            #options: options,
          },
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<void> publishPayload({
    required Map<String, dynamic>? payload,
    required _i38.PublishOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishPayload,
          [],
          {
            #payload: payload,
            #options: options,
          },
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<String> subscribe({required _i38.SubscribeOptions? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [],
          {#options: options},
        ),
        returnValue: _i28.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #subscribe,
            [],
            {#options: options},
          ),
        )),
      ) as _i28.Future<String>);

  @override
  _i28.Future<void> unsubscribe({required String? topic}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsubscribe,
          [],
          {#topic: topic},
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<void> connect({String? relayUrl}) => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
          {#relayUrl: relayUrl},
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i28.Future<void>.value(),
        returnValueForMissingStub: _i28.Future<void>.value(),
      ) as _i28.Future<void>);

  @override
  _i28.Future<bool> handleLinkModeMessage(
    String? topic,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleLinkModeMessage,
          [
            topic,
            message,
          ],
        ),
        returnValue: _i28.Future<bool>.value(false),
      ) as _i28.Future<bool>);

  @override
  _i28.Future<bool> handlePublish(
    String? topic,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handlePublish,
          [
            topic,
            message,
          ],
        ),
        returnValue: _i28.Future<bool>.value(false),
      ) as _i28.Future<bool>);
}
