# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ci
permissions:
  contents: read

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:
    inputs:
      integration:
        description: 'Run integration tests?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      maestro:
        description: 'Run maestro tests?'
        required: false
        default: 'android'
        type: choice
        options:
          - 'android'
          - 'ios'
          - 'both'
          - 'none'

concurrency:
  # Support push/pr as event types with different behaviors each:
  # 1. push: queue up builds by branch
  # 2. pr: only allow one run per PR
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref_name }}
  # If there is already a workflow running for the same pull request, cancel it
  # For non-PR triggers queue up builds
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  tests:
    # strategy:
    #   matrix:
    #     include:
    #       - test-type: integration-tests
    #         runner: macos-14
    #       - test-type: maestro-tests
    #         runner: ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4
  
      # Install Java 17
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          architecture: x86_64
          cache: 'gradle'
  
      # Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      # Install Flutter and Dependencies
      - uses: ./.github/actions/dependencies

      - name: Run Integration Tests
        if: github.event.inputs.integration == 'true'
        uses: ./.github/actions/ci
        with:
          type: "integration-tests"
          relay-endpoint: "wss://relay.walletconnect.org"
          project-id: ${{ secrets.DAPP_PROJECT_ID }}
          wallet-project-id: ${{ secrets.WALLET_PROJECT_ID }}
          secrets-file: ${{ secrets.SECRETS_FILE }}
          keystore: ${{ secrets.KEYSTORE }}

      - name: Run Tests
        if: github.event.inputs.maestro != 'none'
        uses: ./.github/actions/ci
        with:
          type: "maestro-tests"
          platform: ${{ github.event.inputs.maestro }}
          relay-endpoint: "wss://relay.walletconnect.org"
          project-id: ${{ secrets.DAPP_PROJECT_ID }}
          wallet-project-id: ${{ secrets.WALLET_PROJECT_ID }}
          secrets-file: ${{ secrets.SECRETS_FILE }}
          keystore: ${{ secrets.KEYSTORE }}


# Launch locally
# act --container-architecture linux/amd64 -P ubuntu-latest=-self-hosted --secret-file .github/workflows/.env.secret -W .github/workflows/ci.yml workflow_dispatch --input integration=false --input maestro=android
