# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ci
permissions:
  contents: read

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:
    inputs:
      integration:
        description: 'Run integration tests?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      maestro:
        description: 'Run maestro tests?'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

concurrency:
  # Support push/pr as event types with different behaviors each:
  # 1. push: queue up builds by branch
  # 2. pr: only allow one run per PR
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref_name }}
  # If there is already a workflow running for the same pull request, cancel it
  # For non-PR triggers queue up builds
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  tests:
    # strategy:
    #   matrix:
    #     include:
    #       - test-type: integration-tests
    #         runner: macos-14
    #       - test-type: maestro-tests
    #         runner: ubuntu-latest
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      - name: Run Integration Tests
        if: github.event.inputs.integration == 'true'
        uses: ./.github/actions/ci
        with:
          type: "integration-tests"
          relay-endpoint: "wss://relay.walletconnect.org"
          project-id: ${{ secrets.DAPP_PROJECT_ID }}
          wallet-project-id: ${{ secrets.WALLET_PROJECT_ID }}

      - name: Run Tests
        if: github.event.inputs.maestro == 'true'
        uses: ./.github/actions/ci
        with:
          type: "maestro-tests"
          relay-endpoint: "wss://relay.walletconnect.org"
          project-id: ${{ secrets.DAPP_PROJECT_ID }}
          wallet-project-id: ${{ secrets.WALLET_PROJECT_ID }}


# Launch locally
# act --container-architecture linux/amd64 -P macos-14=-self-hosted --secret-file .github/workflows/.env.secret -W .github/workflows/ci.yml workflow_dispatch --input integration=false --input maestro=true
