# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ci

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:
    inputs:
      relay-endpoint:
        description: 'The endpoint of the relay e.g. relay.walletconnect.org'
        required: false
        default: 'wss://relay.walletconnect.org'
      project-id:
        description: 'Reown project id'
        required: true

concurrency:
  # Support push/pr as event types with different behaviors each:
  # 1. push: queue up builds by branch
  # 2. pr: only allow one run per PR
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref_name }}
  # If there is already a workflow running for the same pull request, cancel it
  # For non-PR triggers queue up builds
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: macos-latest
    # runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        test-type: [integration-tests, maestro-tests]
        # os: 
        #   - ubuntu-latest  # For integration-tests (Flutter unit/integration tests)
        #   - macos-latest  # For maestro-tests (iOS UI tests)

    steps:
    - uses: actions/checkout@v3

    - name: Install and set Flutter version
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'

    - uses: ./.github/actions/ci
      if: matrix.test-type == 'integration-tests'
      with:
        type: ${{ matrix.test-type }}
        relay-endpoint: ${{ github.event.inputs.relay-endpoint || 'wss://relay.walletconnect.org' }}
        project-id: ${{ github.event.inputs.project-id || secrets.DAPP_PROJECT_ID }}
    
    - uses: ./.github/actions/ci
      if: matrix.test-type == 'maestro-tests'
      with:
        type: ${{ matrix.test-type }}
        project-id: ${{ github.event.inputs.project-id || secrets.DAPP_PROJECT_ID }}
        wallet-project-id: ${{ secrets.WALLET_PROJECT_ID }}


# Launch locally
# act -j build --container-architecture linux/amd64 -P macos-latest-xlarge=-self-hosted --secret-file .github/workflows/.env.secret -W .github/workflows/ci.yml
# act --container-architecture linux/amd64 -P macos-latest-xlarge=-self-hosted --secret-file .github/workflows/.env.secret -W .github/workflows/ci.yml workflow_dispatch
