name: Android Dapp (production) deploy

on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - closed

# inputs:
# working-directory
# flavor
# BUNDLE_ID

jobs:
  build:
    # if: (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master') || github.event_name == 'workflow_dispatch'
    runs-on: macos-14

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up environment 
      - uses: ./.github/actions/dependencies

      # Add Secrets file on dapp
      - name: Add Secrets file
        working-directory: packages/reown_appkit/example/base/android
        run: touch secrets.properties && echo "${{ secrets.SECRETS_FILE }}" >> secrets.properties

      # Add Keystore file on dapp
      - name: Add Keystore file
        working-directory: packages/reown_appkit/example/base/android
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode >> app/debug.keystore
      
      # Fastlane
      - name: Fastlane
        working-directory: packages/reown_appkit/example/base/android
        env:
          FLAVOR: "production"
          PROJECT_ID: ${{ secrets.DAPP_PROJECT_ID }}
          SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_DAPP_ID: ${{ secrets.FIREBASE_DAPP_ID }}
          DOWNLOAD_URL: ${{ secrets.DOWNLOAD_URL_DAPP }}
        run: |
          PUBSPEC_FILE=../../../pubspec.yaml
          FILE_VALUE=$(echo | grep "^version: " $PUBSPEC_FILE)
          PARTS=(${FILE_VALUE//:/ })
          FULL_VERSION=${PARTS[1]}
          VERSION_NUMBER=(${FULL_VERSION//-/ })

          fastlane add_plugin firebase_app_distribution
          fastlane release_firebase project_id:$PROJECT_ID app_version:$VERSION_NUMBER

# Launch locally
# Remove build: if:
# act -j build --container-architecture linux/amd64 -P macos-14=-self-hosted --secret-file .github/workflows/.env.secret -W .github/workflows/release_dapp_android.yml
# act --container-architecture linux/amd64 -P macos-14=-self-hosted --secret-file .github/workflows/.env.secret -W .github/workflows/release_dapp_android.yml workflow_dispatch
